use std::io::Write;
use std::{
    env, fs,
    path::Path,
    process::{Command, Stdio},
};

use crate::build_lib::language_config::{LanguageConfig, discover_languages};

/// Format generated Rust source using the `rustfmt` binary, reading from stdin.
///
/// If `rustfmt` is unavailable or fails, the original content is returned
/// unformatted so that a real change is still persisted.
fn format_rust_content(content: &str) -> String {
    let mut child = match Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
    {
        Ok(child) => child,
        Err(_) => {
            eprintln!("Warning: rustfmt not found; writing unformatted generated code.");
            return content.to_string();
        }
    };

    if child
        .stdin
        .as_mut()
        .and_then(|stdin| stdin.write_all(content.as_bytes()).ok())
        .is_none()
    {
        eprintln!("Warning: failed to write to rustfmt; writing unformatted generated code.");
        return content.to_string();
    }

    match child.wait_with_output() {
        Ok(output) if output.status.success() => {
            String::from_utf8(output.stdout).unwrap_or_else(|_| content.to_string())
        }
        _ => {
            eprintln!("Warning: rustfmt failed; writing unformatted generated code.");
            content.to_string()
        }
    }
}

/// Write `content` to `dest` only when it differs from the file that already
/// exists on disk. This keeps the source tree clean and avoids needless
/// rebuilds when generated output has not actually changed.
fn write_if_changed(dest: &Path, content: &str) {
    let formatted = format_rust_content(content);

    if let Ok(existing) = fs::read_to_string(dest)
        && existing == formatted
    {
        return;
    }

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent).unwrap();
    }

    fs::write(dest, formatted).unwrap();
}

/// Helper function to generate parse_language match arms dynamically
fn generate_parse_language_match_arms(languages: &[LanguageConfig]) -> String {
    let mut code = String::new();

    // Handle English language parsing - always included
    if let Some(english_lang) = languages.iter().find(|lang| lang.dir_name == "english") {
        for (aliases, dialect_name) in &english_lang.dialect_alias_groups {
            let aliases_str = aliases.join("\" | \"");
            code.push_str(&format!("        \"{}\" => {{\n", aliases_str));
            code.push_str(&format!(
                "            Some(Language::English(EnglishDialect::try_from_abbr(\"{}\").unwrap()))\n",
                dialect_name
            ));
            code.push_str("        }\n");
        }
    }

    // Handle other languages
    for lang in languages {
        if lang.dir_name == "english" {
            continue; // English already handled above
        }

        for (aliases, dialect_name) in &lang.dialect_alias_groups {
            let aliases_str = aliases.join("\" | \"");

            // Add conditional compilation for non-English languages
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }

            // Add the match arm
            code.push_str(&format!("        \"{}\" => {{\n", aliases_str));
            code.push_str(&format!(
                "            Some(Language::{}({}Dialect::try_from_abbr(\"{}\").unwrap()))\n",
                lang.name, lang.name, dialect_name
            ));
            code.push_str("        }\n");
        }
    }

    code
}

/// Generate language module file that contains all language-specific code
/// This consolidates all the #[cfg(feature)] attributes into one place
pub fn generate_language_modules(_out_dir: &Path) {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let src_dir = manifest_dir.join("src/language");

    // Discover all languages dynamically
    let languages = discover_languages(manifest_dir);

    let mut code = String::new();

    // Add header
    code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    code.push_str("// This file centralizes all language-specific conditional compilation\n\n");

    // Generate module declarations
    code.push_str("pub mod dialects;\n");
    code.push_str("pub mod languages;\n");
    code.push_str("pub mod module;\n");
    code.push_str("pub mod morphology;\n");
    code.push_str("pub mod registry;\n\n");

    // English is always included
    code.push_str("pub mod english;\n\n");

    // Optional language modules - generated from discovered languages
    for lang in &languages {
        if lang.feature.is_some() {
            // Skip English as it's already included
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("#[cfg(feature = \"{}\")]\n", feature));
                code.push_str(&format!("pub mod {};\n\n", lang.dir_name));
            }
        }
    }

    // Re-exports
    code.push_str("pub use languages::{Language, LanguageFamily, parse_language};\n");
    code.push_str("pub use module::{LanguageDetector, LanguageModule};\n");
    code.push_str(
        "pub use morphology::{Agreement, Case, Gender, Mood, Morphology, MorphologyExt, Number};\n",
    );
    code.push_str("pub use registry::{\n");
    code.push_str(
        "    ProseLanguage, add_language_specific_linters, detect_language, dictionary,\n",
    );
    code.push_str("    dictionary_for_language, new_curated_for_language, parser_for_prose, prose_language,\n");
    code.push_str("    weir_rules_lint_group,\n");
    code.push_str("};\n");

    // Write directly to mod.rs to replace the hand-written file
    let dest = src_dir.join("mod.rs");
    fs::create_dir_all(&src_dir).unwrap();
    write_if_changed(&dest, &code);

    // Also generate languages.rs
    generate_languages_file(&src_dir, &languages);

    // Re-run the build when language configuration or module files change, not
    // when the files this build script writes change (that would cause a
    // rebuild loop).
    for lang in &languages {
        println!(
            "cargo:rerun-if-changed=src/language/{}/config.toml",
            lang.dir_name
        );
        println!(
            "cargo:rerun-if-changed=src/language/{}/module.rs",
            lang.dir_name
        );
    }
    println!("cargo:rerun-if-changed=src/language/dialects");
    println!("cargo:rerun-if-changed=build_lib");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Generate languages.rs with all the language-related code
fn generate_languages_file(src_dir: &Path, languages: &[LanguageConfig]) {
    let mut code = String::new();

    // Add auto-generated header
    code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    code.push_str("//! Language support framework for Harper.\n");
    code.push_str("//!\n");
    code.push_str(
        "//! This module provides the core types for supporting multiple languages in Harper,\n",
    );
    code.push_str(
        "//! including language families and specific language variants with dialects.\n",
    );

    // Import Dialect trait for try_from_abbr method
    code.push_str("#[allow(unused_imports)]\n");
    code.push_str("use crate::language::dialects::dialect_trait::Dialect;\n\n");

    // English is always included
    code.push_str("use crate::language::english::dialects::EnglishDialect;\n\n");

    // Optional language dialect imports - generated from discovered languages
    for lang in languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("#[cfg(feature = \"{}\")]\n", feature));
            code.push_str(&format!(
                "use crate::language::{}::dialects::{}Dialect;\n\n",
                lang.dir_name, lang.name
            ));
        }
    }
    code.push_str("use serde::{Deserialize, Serialize};\n");
    code.push_str("use strum_macros::{Display, EnumCount, EnumIter, EnumString};\n\n");

    // parse_language function - dynamically generated
    code.push_str("/// Parse a language from a string representation.\n");
    code.push_str("pub fn parse_language(s: &str) -> Option<Language> {\n");
    code.push_str("    let s_lower = s.to_ascii_lowercase();\n\n");
    code.push_str("    match s_lower.as_str() {\n");

    // Use helper function to generate parse language logic
    let parse_language_code = generate_parse_language_match_arms(languages);
    code.push_str(&parse_language_code);

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Language enum
    code.push_str("/// A specific language with its dialects.\n");
    code.push_str("#[derive(\n");
    code.push_str("    Debug, Clone, Copy, Serialize, Deserialize, PartialEq, PartialOrd, Eq, Hash, EnumCount, Display,\n");
    code.push_str(")]\n");
    code.push_str("pub enum Language {\n");

    // Generate Language enum variants dynamically
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("    /// English language with its dialects\n");
            code.push_str("    English(EnglishDialect),\n");
        } else {
            code.push_str(&format!(
                "    /// {} language with its dialects\n",
                lang.name
            ));
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("    {}({}Dialect),\n", lang.name, lang.name));
        }
    }
    code.push_str("}\n\n");

    // LanguageFamily enum
    code.push_str("/// A family of languages.\n");
    code.push_str("#[derive(\n");
    code.push_str("    Default,\n");
    code.push_str("    Debug,\n");
    code.push_str("    Clone,\n");
    code.push_str("    Copy,\n");
    code.push_str("    Serialize,\n");
    code.push_str("    Deserialize,\n");
    code.push_str("    PartialEq,\n");
    code.push_str("    PartialOrd,\n");
    code.push_str("    Eq,\n");
    code.push_str("    Hash,\n");
    code.push_str("    EnumCount,\n");
    code.push_str("    EnumString,\n");
    code.push_str("    EnumIter,\n");
    code.push_str("    Display,\n");
    code.push_str(")]\n");
    code.push_str("pub enum LanguageFamily {\n");

    // Generate LanguageFamily enum variants dynamically
    for (i, lang) in languages.iter().enumerate() {
        if i == 0 {
            code.push_str("    #[default]\n");
        }
        if lang.dir_name == "english" {
            code.push_str("    English,\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("    {},\n", lang.name));
        }
    }
    code.push_str("}\n\n");

    // From<Language> for LanguageFamily
    code.push_str("impl From<Language> for LanguageFamily {\n");
    code.push_str("    fn from(value: Language) -> Self {\n");
    code.push_str("        match value {\n");

    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("            Language::English(_) => Self::English,\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!(
                "            Language::{}(_) => Self::{},\n",
                lang.name, lang.name
            ));
        }
    }
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // LanguageFamily impl
    code.push_str("impl LanguageFamily {\n");
    code.push_str("    pub fn dict_suffix(&self) -> &'static str {\n");
    code.push_str("        match self {\n");

    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("            Self::English => \"\",\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!(
                "            Self::{0} => \"-{1}\",\n",
                lang.name,
                feature_to_suffix(lang)
            ));
        }
    }
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Language impl
    code.push_str("impl Language {\n");
    code.push_str("    pub fn family(&self) -> LanguageFamily {\n");
    code.push_str("        (*self).into()\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("impl Default for Language {\n");
    code.push_str("    fn default() -> Self {\n");
    code.push_str("        Self::English(EnglishDialect::American)\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    let dest = src_dir.join("languages.rs");
    write_if_changed(&dest, &code);

    // Also generate registry.rs
    generate_registry_file(src_dir, languages);
}

/// Helper function to convert feature name to dict suffix
/// e.g., "de" -> "de", "pt" -> "pt", "sk" -> "sk"
fn feature_to_suffix(lang: &LanguageConfig) -> String {
    if let Some(feature) = &lang.feature {
        feature.to_string()
    } else if lang.dir_name == "english" {
        "en".to_string()
    } else {
        lang.dir_name.to_string()
    }
}

/// Generate registry.rs with all language-specific registry code
fn generate_registry_file(src_dir: &Path, languages: &[LanguageConfig]) {
    let mut code = String::new();

    // Add auto-generated header
    code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    code.push_str(
        "//! Language registry - central integration point using LanguageModule trait.\n",
    );
    code.push_str("//!\n");
    code.push_str("//! This module provides all orchestration functions for language support.\n");
    code.push_str(
        "//! It is the only place that imports concrete language module implementations.\n\n",
    );

    code.push_str("use std::fmt::Debug;\n");
    code.push_str("use std::sync::{Arc, LazyLock};\n\n");

    code.push_str("use super::languages::{Language, LanguageFamily};\n");
    code.push_str("use crate::spell::Dictionary;\n");
    code.push_str("use crate::{\n");
    code.push_str("    parsers::{Markdown, MarkdownOptions, OrgMode, Parser},\n");
    code.push_str("    LintGroup,\n");
    code.push_str("};\n\n");

    code.push_str("use super::english::module::EnglishModule;\n");
    code.push_str("use super::module::{LanguageDetector, LanguageModule};\n\n");

    // Import all language modules dynamically
    for lang in languages {
        if lang.dir_name == "english" {
            continue; // English already imported above
        }

        if let Some(feature) = &lang.feature {
            code.push_str(&format!("#[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!(
            "use super::{}::module::{}Module;\n\n",
            lang.dir_name, lang.name
        ));
    }

    // DETECTION
    code.push_str("/// All language detectors, sorted by confidence (highest to lowest).\n");
    code.push_str("#[allow(clippy::vec_init_then_push)]\n");
    code.push_str(
        "static DETECTORS: LazyLock<Vec<(Box<dyn LanguageDetector>, f64)>> = LazyLock::new(|| {\n",
    );
    code.push_str("    let mut detectors: Vec<(Box<dyn LanguageDetector>, f64)> = Vec::new();\n\n");

    // Generate detector registrations dynamically, sorted by confidence (highest first)
    let mut sorted_languages = languages.to_vec();
    sorted_languages.sort_by(|a, b| {
        b.confidence
            .partial_cmp(&a.confidence)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    for lang in &sorted_languages {
        if lang.dir_name == "english" {
            continue; // English detector added last (lowest confidence)
        }

        if let Some(feature) = &lang.feature {
            code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!(
            "    detectors.push((Box::new({}Module::detector()), {:.2}));\n\n",
            lang.name, lang.confidence
        ));
    }

    // English detector always added last
    code.push_str("    detectors.push((Box::new(EnglishModule::detector()), 0.30));\n\n");
    code.push_str("    detectors\n");
    code.push_str("});\n\n");

    // detect_language function
    code.push_str("/// Detect the language of the given source text.\n");
    code.push_str("pub fn detect_language(source: &str, dict: &dyn Dictionary, default_language: Language) -> Language {\n");
    code.push_str("    use crate::language::languages::Language;\n");
    code.push_str("    use crate::parsers::PlainEnglish;\n\n");
    code.push_str("    let source_chars: Vec<char> = source.chars().collect();\n");
    code.push_str("    let tokens = PlainEnglish.parse(&source_chars);\n\n");

    code.push_str("    if tokens.is_empty() {\n");
    code.push_str("        return default_language;\n");
    code.push_str("    }\n\n");

    code.push_str("    for (detector, _confidence) in DETECTORS.iter() {\n");
    code.push_str(
        "        if let Some(language) = detector.detect(&tokens, &source_chars, dict) {\n",
    );
    code.push_str(
        "            // Special handling for English: if the default language is also English,\n",
    );
    code.push_str("            // use the default language (which includes the configured dialect) instead of\n");
    code.push_str("            // the detector's hardcoded American dialect.\n");
    code.push_str("            if matches!(language, Language::English(_)) && matches!(default_language, Language::English(_)) {\n");
    code.push_str("                return default_language;\n");
    code.push_str("            }\n");
    code.push_str("            return language;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    default_language\n");
    code.push_str("}\n\n");

    // PROSE LANGUAGE
    code.push_str("/// Prose languages supported by Harper for text parsing.\n");
    code.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
    code.push_str("pub enum ProseLanguage {\n");

    // Generate ProseLanguage enum variants dynamically
    for (i, lang) in languages.iter().enumerate() {
        if i > 0
            && let Some(feature) = &lang.feature
        {
            code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("    {},", lang.name));
        if i < languages.len() - 1 {
            code.push('\n');
        }
    }
    code.push_str("}\n\n");

    code.push_str("/// Convert a Harper Language to a ProseLanguage.\n");
    code.push_str("pub fn prose_language(language: &Language) -> ProseLanguage {\n");
    code.push_str("    match language {\n");

    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        Language::English(_) => ProseLanguage::English,\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!(
                "        Language::{}(_) => ProseLanguage::{},\n",
                lang.name, lang.name
            ));
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // DICTIONARIES
    code.push_str("/// Get the dictionary for a language family.\n");
    code.push_str(
        "pub fn dictionary_for_language(family: LanguageFamily) -> Arc<dyn Dictionary> {\n",
    );
    code.push_str("    match family {\n");

    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        LanguageFamily::English => EnglishModule::dictionary(),\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!(
                "        LanguageFamily::{0} => {1}Module::dictionary(),\n",
                lang.name, lang.name
            ));
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("/// Get the dictionary for a language.\n");
    code.push_str("pub fn dictionary(language: Language) -> Arc<dyn Dictionary> {\n");
    code.push_str("    dictionary_for_language(language.family())\n");
    code.push_str("}\n\n");

    // PARSERS
    code.push_str("/// Get a parser for the given language ID and language.\n");
    code.push_str("pub fn parser_for_prose(\n");
    code.push_str("    language_id: &str,\n");
    code.push_str("    language: Language,\n");
    code.push_str("    markdown_options: MarkdownOptions,\n");
    code.push_str(") -> Option<Box<dyn Parser>> {\n");
    code.push_str("    match (language_id, prose_language(&language)) {\n");

    // Mail format parsers
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        (\"mail\", ProseLanguage::English) => Some(Box::new(EnglishModule::plain_parser())),\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!(
                "        (\"mail\", ProseLanguage::{0}) => Some(Box::new({1}Module::plain_parser())),\n",
                lang.name,
                lang.name
            ));
        }
    }
    code.push('\n');
    code.push_str("        // Markdown/Quarto format\n");

    // Markdown parsers for non-English languages
    for lang in languages {
        if lang.dir_name == "english" {
            continue;
        }

        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!(
            "        (\"markdown\" | \"quarto\", ProseLanguage::{0}) => Some(Box::new(\n",
            lang.name
        ));
        code.push_str("            Markdown::with_inline_parser(markdown_options, |source| {\n");
        code.push_str(&format!(
            "                {}Module::plain_parser().parse(source)\n",
            lang.name
        ));
        code.push_str("            }),\n");
        code.push_str("        )),\n");
    }
    code.push_str("        (\"markdown\" | \"quarto\", _) => Some(Box::new(Markdown::new(markdown_options))),\n");
    code.push('\n');
    code.push_str("        // Org mode format\n");

    // Org mode parsers for non-English languages
    for lang in languages {
        if lang.dir_name == "english" {
            continue;
        }

        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("        (\"org\", ProseLanguage::{0}) => Some(Box::new(OrgMode::with_inline_parser(|source| {{\n", lang.name));
        code.push_str(&format!(
            "            {}Module::plain_parser().parse(source)\n",
            lang.name
        ));
        code.push_str("        }))),\n");
    }
    code.push_str("        (\"org\", _) => Some(Box::new(OrgMode::default())),\n");
    code.push('\n');
    code.push_str("        // Plain text format\n");

    // Plain text parsers
    for lang in languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!(
            "        (\"plaintext\" | \"text\", ProseLanguage::{0}) => {{\n",
            lang.name
        ));
        code.push_str(&format!(
            "            Some(Box::new({}Module::plain_parser()))\n",
            lang.name
        ));
        code.push_str("        }\n");
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // LINTERS
    code.push_str("/// Add language-specific linters to the lint group.\n");
    code.push_str("pub fn add_language_specific_linters(\n");
    code.push_str("    out: &mut LintGroup,\n");
    code.push_str("    language: Language,\n");
    code.push_str("    dictionary: Arc<impl Dictionary + 'static>,\n");
    code.push_str(") {\n");
    code.push_str("    match language {\n");

    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        Language::English(_dialect) => {\n");
            code.push_str(
                "            let lang_group = EnglishModule::rust_lint_group(dictionary);\n",
            );
            code.push_str("            out.merge_from(lang_group);\n");
            code.push_str("        }\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("        Language::{}(_) => {{\n", lang.name));
            code.push_str(&format!(
                "            let lang_group = {}Module::rust_lint_group(dictionary);\n",
                lang.name
            ));
            code.push_str("            out.merge_from(lang_group);\n");
            code.push_str("        }\n");
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // WIR RULES
    code.push_str("/// Get the Weir rule lint group for a specific language.\n");
    code.push_str("pub fn weir_rules_lint_group(language: Language) -> LintGroup {\n");
    code.push_str("    match language {\n");

    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        Language::English(_) => EnglishModule::weir_lint_group(),\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!(
                "        Language::{}(_) => {}Module::weir_lint_group(),\n",
                lang.name, lang.name
            ));
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // CURATED LINT GROUPS
    code.push_str(
        "/// Create a new curated lint group for a specific language with a custom dictionary.\n",
    );
    code.push_str("pub fn new_curated_for_language(\n");
    code.push_str("    dictionary: Arc<impl Dictionary + 'static>,\n");
    code.push_str("    language: Language,\n");
    code.push_str(") -> LintGroup {\n");
    code.push_str("    use crate::language::module::LanguageModule;\n\n");

    code.push_str("    match language {\n");

    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        Language::English(_dialect) => {\n");
            code.push_str("            EnglishModule::curated_lint_group(_dialect, dictionary)\n");
            code.push_str("        }\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("        Language::{}(dialect) => {{\n", lang.name));
            code.push_str(&format!(
                "            use crate::language::{}::module::{}Module;\n\n",
                lang.dir_name, lang.name
            ));
            code.push_str(&format!(
                "            {}Module::curated_lint_group(dialect, dictionary)\n",
                lang.name
            ));
            code.push_str("        }\n");
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n");

    let dest = src_dir.join("registry.rs");
    write_if_changed(&dest, &code);
}
