//! Tests that declined adjective forms keep an adjective reading.
//!
//! German adjectives inflect for case, gender and number (`deutsch` ->
//! `deutsche`, `deutschen`, `deutscher`, ...). Those forms are generated by the
//! declension affixes in `annotations.json`.
//!
//! Many of the same spellings are also nouns -- `deutsche` is both the declined
//! adjective in *"eine einfache deutsche Testdatei"* and the nominalized noun in
//! *"Dieses Buch ist nur für Deutsche"*. `GermanNounCapitalization` relies on
//! that ambiguity: a word with only a noun reading is flagged wherever it
//! appears, while a word that is also an adjective is flagged only when its left
//! context licenses a noun phrase.
//!
//! So a declined adjective that arrives carrying *only* a noun reading gets
//! flagged in ordinary attributive use. These tests pin the adjective reading.

#[cfg(test)]
mod tests {
    use crate::Document;
    use crate::language::german::dialects::GermanDialect;
    use crate::language::german::linting::new_curated_german;
    use crate::language::german::parsers::PlainGerman;
    use crate::language::german::spell::curated_german_dictionary;
    use crate::linting::Linter;
    use crate::spell::Dictionary;

    /// Every declined form of a common adjective must carry an adjective reading.
    #[test]
    fn declined_adjectives_keep_their_adjective_reading() {
        let dict = curated_german_dictionary();

        // base form, then the -e/-er/-es/-em/-en declension paradigm
        for word in [
            "deutsch",
            "deutsche",
            "deutscher",
            "deutsches",
            "deutschem",
            "deutschen",
            "klein",
            "kleine",
            "kleiner",
            "kleines",
            "schnell",
            "schnelle",
            "schneller",
        ] {
            let metadata = dict
                .get_word_metadata_str(word)
                .unwrap_or_else(|| panic!("'{word}' should be in the German dictionary"));

            assert!(
                metadata.is_adjective(),
                "'{word}' is a declined adjective and must carry an adjective reading; \
                 without one GermanNounCapitalization treats it as an unambiguous noun"
            );
        }
    }

    fn lints_for(text: &str) -> Vec<String> {
        let dict = curated_german_dictionary();
        let mut linter = new_curated_german(GermanDialect::Standard, dict.clone());
        let document = Document::new(text, &PlainGerman, &dict);

        linter
            .lint(&document)
            .into_iter()
            .map(|lint| document.get_span_content_str(&lint.span))
            .collect()
    }

    /// An attributive adjective after another adjective is not a noun.
    #[test]
    fn attributive_adjective_is_not_flagged_as_a_noun() {
        let flagged = lints_for("Dies ist eine einfache deutsche Testdatei für Harper.");

        assert!(
            !flagged.iter().any(|word| word == "deutsche"),
            "'deutsche' is attributive here and must not be flagged; flagged: {flagged:?}"
        );
        assert!(
            !flagged.iter().any(|word| word == "einfache"),
            "'einfache' is attributive here and must not be flagged; flagged: {flagged:?}"
        );
    }

    /// The nominalized reading, licensed by a preposition, still gets flagged.
    #[test]
    fn nominalized_adjective_after_preposition_is_still_flagged() {
        let flagged = lints_for("Dieses Buch ist nur für deutsche.");

        assert!(
            flagged.iter().any(|word| word == "deutsche"),
            "'deutsche' after the preposition 'für' is a nominalized noun and should be \
             flagged for capitalization; flagged: {flagged:?}"
        );
    }
}
